services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-go:stable-1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASSWORD: password  # Ensure this matches MYSQL_ROOT_PASSWORD below
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: projectmanager
      JWT_SECRET: randomjwtsecretkey
    networks:
      - app-network

  db:
    image: mysql:latest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: projectmanagerDB
    environment:
      MYSQL_ROOT_PASSWORD: password  # Set the root password for MySQL, ensure this matches DB_PASSWORD above
      MYSQL_DATABASE: projectmanager  # Create a default database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
